name: Deploy ADF

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: delete repo path
      run: rm -rf ${{ github.workspace }}/*
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Print repo path
      run: ls ${{ github.workspace }}/
    - name: Login to Azure
      run: az login
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1.0.6
      with:
        scope: 'resourcegroup'
        resourceGroupName: 'testResource'
        template: ${{ github.workspace }}/ARMTemplateForFactory.json
        parameters: ${{ github.workspace }}/ARMTemplateParametersForFactory.json
        deploymentMode: Incremental
        
